apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - protocol: 'TCP'
    port: 80
    targetPort: 80
        
