apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deployment-final
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app
  template: 
    metadata:
      labels:
        app: nginx-app
    spec: 
      containers:
      - name: nginx-app-container
        image: estrucmarcelo/index-nginx:2